<?php
$api = Mage::getSingleton('Youstice_YousticeResolutionSystem_Helper_ApiSingleton')->get();

$titleString = Mage::app()->getStore()->getName() . ' - Youstice - ' . $api->t('File a complaint');
$html = '<meta property="og:title" content="' . $titleString . '" />';
$html .= '<meta property="og:type" content="website" />';
$html .= '<meta property="og:url" content="' . $this->getUrl('youstice/index/getReportClaimsPage') . '" />';
$html .= '<meta property="og:image" content="' . Mage::getDesign()->getSkinUrl('images/youstice/logo.png') . '" />';

$description_text = $api->t("In case you want to complain about a product or service, please follow this link.");
$html .= '<meta property="og:description" content="' . $description_text . '" />';
echo $html;